### ISSUE TITLE
"account has not default VPC" output despite specifying x-aws-vpc as top-level element in docker-compose.yml.

### ISSUE THREAD

**Issue by mbartlet** [docker/ecs-plugin#200] opened 2020-07-31 23:33 UTC
It's true the AWS account I'm using doesn't have a default VPC, but I would assume specifying the VPC ID would be sufficient.

Here are the relevant contents of my docker-compose.yml:
```yaml
version: '3.8'
x-aws-vpc: vpc-*******
x-aws-loadbalancer: my-load-balancer-name
x-aws-cluster: my-cluster-name

services:
...
```

With this configuration I get the following terminal session:
```sh
$ ls
docker-compose.yml

$ docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
ecs *                aws                                                                                                               

$ docker ecs compose up
account has not default VPC
```

I am not sure what other files or content may be useful to add here but I am happy to provide more information upon request.

**Comment by ndeloof** [comment] 2020-08-03 07:38
I was not able to reproduce this issue.

**Comment by mbartlet** [comment] 2020-08-03 15:37
If relevant, my versions:
* Docker version 19.03.12, build 48a66213fe
* docker-compose version 1.26.2, build eefe0d31
* Docker ECS plugin v1.0.0-beta.2 (6629d8e)

**Comment by ndeloof** [comment] 2020-08-07 14:23
Seems to me this is a duplicate for https://github.com/docker/ecs-plugin/issues/184, fixed in beta.4

**Closed by ndeloof** 2020-08-07 14:23 UTC
